# Generated by Django 3.1.2 on 2021-06-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectname', models.CharField(max_length=100)),
                ('goalname', models.CharField(max_length=100)),
                ('targetrank', models.IntegerField()),
                ('targetscore', models.IntegerField()),
                ('targetdate', models.DateTimeField()),
                ('currentscore', models.IntegerField()),
                ('improvepercentage', models.IntegerField()),
                ('student', models.CharField(max_length=100)),
            ],
        ),
    ]
