# Generated by Django 3.1.2 on 2021-06-02 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0002_home2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home2',
            new_name='Goal',
        ),
        migrations.RenameModel(
            old_name='Home',
            new_name='Student',
        ),
    ]
