# Generated by Django 3.1.2 on 2021-06-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0003_auto_20210602_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='targetdate',
            field=models.DateField(),
        ),
    ]
