# Generated by Django 3.1.2 on 2021-06-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0004_auto_20210603_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='targetdate',
            field=models.DateTimeField(),
        ),
    ]
