# Generated by Django 3.1.2 on 2021-06-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0005_auto_20210603_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='improvepercentage',
            field=models.CharField(max_length=100),
        ),
    ]
