# Generated by Django 3.1.2 on 2021-06-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0006_auto_20210603_1231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='improvepercentage',
            new_name='nameofexam',
        ),
    ]
