# Generated by Django 3.1.2 on 2021-06-04 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0007_auto_20210603_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='some',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sam.student'),
        ),
    ]
