# Generated by Django 3.1.2 on 2021-06-04 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sam', '0008_goal_some'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='some',
            new_name='name',
        ),
    ]
